### ISSUE TITLE
Cassandra Sink with Amazon Keyspaces-ERROR WorkerSinkTask{id=datastax-connector-json-0} Task threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask) java.lang.RuntimeException: Prepare failed for statement: INSERT INTO lake_iot.test2(datacontent) VALUES (:datacontent) USING TIMESTAMP :kafka_internal_timestamp or DELETE FROM lake_iot.test2 WHERE datacontent = :datacontent

### ISSUE THREAD

**Issue by cph1c06** [DataStax-Examples/kafka-connector-sink-json#1]
I'm attempting to use Cassandra on AWS Amazon Keyspaces and sink data from Kafka into it using the Cassandra Sink. Same exact sink configuration works with regular Cassandra, but fails on Amazon Keyspaces.

Sink Properties:
```
{
  "name": "datastax-connector-json",
  "config": {
    "connector.class": "com.datastax.kafkaconnector.DseSinkConnector",
    "tasks.max": "1",
    "contactPoints": "cassandra.<redacted>.amazonaws.com",
    "port": "9142",
    "loadBalancing.localDc": "<redacted>",
    "auth.provider": "DSE",
    "auth.username": "<redacted>",
    "auth.password": "<redacted>",
    "topics": "json-stream",
    "topic.json-stream.lake.test.mapping": "content=value.id",
    "topic.json-stream.lake.test.consistencyLevel": "LOCAL_QUORUM",
    "topic.json-stream.codec.timeZone": "UTC",
    "topic.json-stream.codec.timestamp": "CQL_TIMESTAMP",
    "ssl.provider": "JDK",
    "ssl.trustStore": "/tmp/cassandra_truststore.jks",
    "ssl.trustStorePassword": "<redacted>"
  }
}
```
The sink is configured with JSON without schema. Target table is created with:
```
create keyspace if not exists lake with replication = {'class': 'SimpleStrategy', 'replication_factor': 1};
CREATE TABLE lake.test (content text PRIMARY KEY);
```
JSON records in the topic match exactly the names and types of the fields in the target table.

When used with regular Cassandra above configuration works as expected. When configured to sink to Cassandra on Amazon Keyspace same configuration fails with the following error:
```
[2020-04-27 03:54:05,146] ERROR WorkerSinkTask{id=datastax-connector-json-0} Task threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask)
java.lang.RuntimeException: Prepare failed for statement: INSERT INTO lake.test(content) VALUES (:content) USING TIMESTAMP :kafka_internal_timestamp or DELETE FROM lake.test WHERE content = :content
	at com.datastax.kafkaconnector.state.LifeCycleManager.lambda$prepareStatementsAsync$14(LifeCycleManager.java:657)
	at java.util.concurrent.CompletableFuture.uniExceptionally(CompletableFuture.java:870)
	at java.util.concurrent.CompletableFuture$UniExceptionally.tryFire(CompletableFuture.java:852)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
	at com.datastax.oss.driver.internal.core.cql.CqlPrepareAsyncProcessor.lambda$process$1(CqlPrepareAsyncProcessor.java:74)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
	at com.datastax.oss.driver.internal.core.cql.CqlPrepareHandler.lambda$setFinalResult$2(CqlPrepareHandler.java:251)
	at java.util.concurrent.CompletableFuture.uniRun(CompletableFuture.java:705)
	at java.util.concurrent.CompletableFuture.uniRunStage(CompletableFuture.java:717)
	at java.util.concurrent.CompletableFuture.thenRun(CompletableFuture.java:2010)
	at java.util.concurrent.CompletableFuture.thenRun(CompletableFuture.java:110)
	at com.datastax.oss.driver.internal.core.cql.CqlPrepareHandler.setFinalResult(CqlPrepareHandler.java:247)
	at com.datastax.oss.driver.internal.core.cql.CqlPrepareHandler.access$600(CqlPrepareHandler.java:76)
	at com.datastax.oss.driver.internal.core.cql.CqlPrepareHandler$InitialPrepareCallback.onResponse(CqlPrepareHandler.java:372)
	at com.datastax.oss.driver.internal.core.channel.InFlightHandler.channelRead(InFlightHandler.java:255)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:287)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:328)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:302)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1475)
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1224)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1271)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:505)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:444)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:283)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1421)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:697)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:632)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:549)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:511)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.datastax.oss.driver.api.core.AllNodesFailedException: All 1 node(s) tried for the query failed (showing first 1 nodes, use getAllErrors() for more): Node(endPoint=cassandra.ap-east-1.amazonaws.com/18.163.201.59:9142, hostId=05deae2d-6405-494d-a965-c0e5836bcb3c, hashCode=7d50dbf3): [com.datastax.oss.driver.api.core.servererrors.ServerError: Internal Server Error]
	at com.datastax.oss.driver.api.core.AllNodesFailedException.fromErrors(AllNodesFailedException.java:55)
	at com.datastax.oss.driver.internal.core.cql.CqlPrepareHandler.sendRequest(CqlPrepareHandler.java:210)
	at com.datastax.oss.driver.internal.core.cql.CqlPrepareHandler.access$400(CqlPrepareHandler.java:76)
	at com.datastax.oss.driver.internal.core.cql.CqlPrepareHandler$InitialPrepareCallback.processRetryDecision(CqlPrepareHandler.java:425)
	at com.datastax.oss.driver.internal.core.cql.CqlPrepareHandler$InitialPrepareCallback.processErrorResponse(CqlPrepareHandler.java:412)
	at com.datastax.oss.driver.internal.core.cql.CqlPrepareHandler$InitialPrepareCallback.onResponse(CqlPrepareHandler.java:375)
	... 35 more
	Suppressed: com.datastax.oss.driver.api.core.servererrors.ServerError: Internal Server Error
[2020-04-27 03:54:05,151] ERROR WorkerSinkTask{id=datastax-connector-json-0} Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask)
[2020-04-27 03:54:05,152] INFO Task is stopped. (com.datastax.kafkaconnector.TaskStateManager)
```

**Comment by adutra** [comment]
Hi,

Your query is invalid, the following CQL statement is not correct: 

```
INSERT INTO lake.test(content) VALUES (:content) USING TIMESTAMP :kafka_internal_timestamp or DELETE FROM lake.test WHERE content = :content
```

There is no `or` keyword in CQL that would allow you to perform an INSERT or a DELETE. It's either one or the other.

Tip: next time, please ask your question in https://community.datastax.com/ , thanks!

**Comment by cph1c06** [comment]
I will ask in the community if I have further questions. Thanks a lot.
